version: '3.4'

services:
  user_manager:
    image: ${DOCKER_REGISTRY-}user_manager
    build:
      context: .
      dockerfile: Messenger.UserManager/Dockerfile
    networks:
      - messenger_net

  message_manager:
    image: ${DOCKER_REGISTRY-}message_manager
    build:
      context: .
      dockerfile: Messenger.MessageManager/Dockerfile
    networks:
      - messenger_net

networks:
  messenger_net:
    external:
      name: messenger_net